### ISSUE TITLE
Missing tool usegalaxy.eu

### ISSUE THREAD

**Issue by orchid00** [galaxyproject/galaxy-hub#403] opened 2018-05-02 14:48 UTC
I'm testing https://usegalaxy.eu/
Tool: Operate on Genomic Intervals
is missing:  **Join** the intervals of two datasets side-by-side

Available options:
- Cluster the intervals of a dataset
- BED to IGV create batch script for taking IGV screenshots
- BAM to BED converter
- AnnotateBed annotate coverage of features from multiple files
- OverlapBed computes the amount of overlap from two intervals
- TagBed tag BAM alignments based on overlaps with interval files
- FlankBed create new intervals from the flanks of existing intervals

----

> Note: I've achieved desired output using Text manipulation > Join the intervals of two datasets side-by-side
----

This issue relates to https://galaxyproject.org/tutorials/g101/

**Comment by tnabtaf** [comment] 2018-05-03 05:31
HI @orchid00, thanks for reporting this, and it looks like @bgruening is addressing this.

@bgruening, @natefoo My first thought when I saw this issue was: The Hub is probably not the best place to post issues with these servers.  But then I couldn't think of where I should ask Paula to resubmit so I just whistled and pretended that I hadn't seen Paula's post...

*Is there a repo we should be pointing people at for synchronization issues?*

**Comment by bgruening** [comment] 2018-05-03 06:59
Hi @tnabtaf,

in this particular issue I guess the problem is that the training is still in the hub. I think we are fine with these reports in the http://training.galaxyproject.org repository.

**Comment by erasche** [comment] 2018-05-03 20:16
We could definitely use biostars, but I don't check that regularly. For minimal friction for end users, I think it makes sense to do whatever main does here and just make sure the instance is tagged so we know when it's us.

**Comment by hexylena** [comment] 2020-10-20 10:10
Closing as it is outdated, we've moved to discourse,  and people generally go there.

**Closed by hexylena** 2020-10-20 10:10 UTC
