### ISSUE TITLE
Keep section quick-ref links visible with page scrolls 

### ISSUE THREAD

**Issue by VJalili** [galaxyproject/galaxy-hub#511] opened 2019-04-05 18:32 UTC
The links on the right side-bar (i.e., the section links) are scrolled up/down with the center panel, hence making them inaccessible when scrolled further down. IMHO it is better to keep this panel visible all the time since it helps navigate the page easily:

![Screen Shot 2019-04-05 at 11 31 52 AM](https://user-images.githubusercontent.com/9027482/55648939-7a4ba700-5796-11e9-8cb0-1bac92d19035.png)

![Screen Shot 2019-04-05 at 11 32 03 AM](https://user-images.githubusercontent.com/9027482/55648948-7f105b00-5796-11e9-9d24-70989f55b864.png)

I am expecting to see the links to "CloudMan", "Cloud Storage", "Globus Genomics", and etc. on the second screenshot.

**Comment by dannon** [comment] 2019-04-05 18:45
There was/is another issue for this somewhere; I think for simplicity we just reverted to pinning it directly.  The problem was that there are some pages where that right list taller than 100%.

If you want to tinker with this, though, certainly feel free.

**Comment by martenson** [comment] 2019-04-05 18:46
duplicate of https://github.com/galaxyproject/galaxy-hub/issues/103

**Closed by martenson** 2019-04-05 18:46 UTC
