### ISSUE TITLE
https://docs.galaxyproject.org needs wiki links updated to point to hub

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy-hub#153] opened 2017-02-23 22:19 UTC
Few examples of link types here: https://docs.galaxyproject.org/en/master/releases/13.04_announce.html

**Comment by martenson** [comment] 2017-02-24 20:59
this is pretty much a duplicate of https://github.com/galaxyproject/galaxy-hub/issues/40 so I am closing it

**Closed by martenson** 2017-02-24 20:59 UTC
Labels: enhancement

**Comment by jennaj** [comment] 2017-02-24 21:19
Ok, that one is about redirects. I was thinking we might want to update our own core rtd with the correct links (at some point) - but you all decide.

**Comment by martenson** [comment] 2017-02-24 21:23
@jennaj proper redirects will save us from editing old links which is a superior solution I think
